import Head from 'next/head'

import SiteHeader from '../components/site-header/SiteHeader'
import '../styles/globals.scss'

export default function MyApp({ Component, pageProps }) {
  return (
    <div className="App">
      <Head>
        <title>Strapi Netninja</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SiteHeader />
      <Component {...pageProps} />
    </div>
  )
}
