import Head from 'next/head'

export default function Home() {
  return (
    <div className="App">
      <Head>
        <title>Strapi Netninja</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
